import { useState } from 'react'
import { Route, Routes, useLocation } from 'react-router-dom'
import { Header, AppShell } from './components/Layout'
import { Toast } from './components/Ui'
import Landing from './pages/Landing'
import About from './pages/About'
import Emergency from './pages/Emergency'
import PrescriptionUpload from './pages/PrescriptionUpload'
import NearbyStore from './pages/NearbyStore'
import Consultation from './pages/Consultation'
import { AuthPage } from './pages/AuthPages'
import { Dashboard, Medicines, MedicineDetail, Profile, Reminders } from './pages/AppPages'
import { initialReminders } from './data/mockData'

export default function App(){ const location=useLocation(), [menu,setMenu]=useState(false),[reminders,setReminders]=useState(initialReminders),[toast,setToast]=useState(''); const appRoute=!['/','/login','/register','/about'].includes(location.pathname); const addToast=text=>{setToast(text);window.setTimeout(()=>setToast(''),2500)}; return <><Header onMenu={()=>setMenu(true)}/>{appRoute?<AppShell open={menu} onClose={()=>setMenu(false)}><Routes><Route path="/dashboard" element={<Dashboard reminders={reminders}/>}/><Route path="/medicines" element={<Medicines/>}/><Route path="/medicines/:id" element={<MedicineDetail addToast={addToast}/>}/><Route path="/profile" element={<Profile addToast={addToast}/>}/><Route path="/reminders" element={<Reminders reminders={reminders} setReminders={setReminders} addToast={addToast}/>}/><Route path="/emergency" element={<Emergency/>}/><Route path="/upload-prescription" element={<PrescriptionUpload/>}/><Route path="/nearby-store" element={<NearbyStore/>}/><Route path="/consultation" element={<Consultation/>}/></Routes></AppShell>:<Routes><Route path="/" element={<Landing/>}/><Route path="/about" element={<About/>}/><Route path="/login" element={<AuthPage/>}/><Route path="/register" element={<AuthPage register/>}/></Routes>}<Toast text={toast}/></> }
